// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Post struct {
	ID        int32
	Title     string
	Content   string
	Category  sql.NullString
	Tags      []string
	Createdat sql.NullTime
	Updatedat sql.NullTime
}

type User struct {
	ID       int32
	Email    string
	Password string
	Role     string
}
